# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Harwell Rocket Club
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  UK based amateur rocket group striving to design, build and launch high power rockets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
media:
  - site: GitHub
    link: https://www.github.com/HarwellRocketClub
    name: HarwellRocketClub
    icon: assets/img/github_24x_24x.png
  - site: Flickr
    link: https://www.flickr.com/photos/188063235@N02/
    name: HarwellRocketClub
    icon: assets/img/flickr_24x_24x.png
  - site: Twitter
    link: https://twitter.com/HarwellRockets
    name: HarwellRockets
    icon: assets/img/twitter_24x_24x.png
  - site: YouTube
    link: https://www.youtube.com/channel/UCIzx-9Uy_lV__uc--MwWsCw
    name: HarwellRocketClub
    icon: assets/img/youtube_24x_24x.png
  - site: Atom feed
    link: /feed.xml
    name: Atom feed
    icon: assets/img/atom_24x_24x.png

logo: assets/img/club_logo.png
# google_analytics: UA-164126166-1

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

default_team_image: assets/img/blackarrow3.jpg

red_kite_description: >-
  RedKite is a series of sounding rockets with the ambition to provide launch capabilities for student projects to approx. 1-3km altitude. 
  The intention of RedKite is to inspire children, students and adult of all ages and backgrounds by providing a platform
  where they are able to design, build and launch their own payloads. The name choice represents the rebirth of the UK rocketry 
  industry following the near extinction of the RedKite bird, which resiliently bounced back. Red-kite's can also be found here at Harwell.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
